---
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  ScopeDetails:
    Type: String
    Default: <na>
  IncludeExcludeScope:
    Type: String
    Default: Include
    AllowedValues:
      - Include
      - Exclude
  ScopeType:
    Type: String
    Description: "Should Firewall Manager Policies be scoped to the entire org (root) or a specific list of OUs (OU)"
    Default: Org
    AllowedValues:
      - Org
      - OU
      - Accounts
  ResourceTagUsage:
    Type: String
    Default: Include
    Description: Include will scope to only include when ResourceTags match, Exclude will exclude when target resource tags match ResourceTags
    AllowedValues:
      - Include
      - Exclude
  ProtectRegionalResourceTypes:
    Type: String
    Description: AWS::ElasticLoadBalancingV2::LoadBalancer,AWS::ElasticLoadBalancing::LoadBalancer,AWS::EC2::EIP
    Default: AWS::ElasticLoadBalancingV2::LoadBalancer,AWS::ElasticLoadBalancing::LoadBalancer,AWS::EC2::EIP
    AllowedValues:
      - AWS::ElasticLoadBalancingV2::LoadBalancer,AWS::ElasticLoadBalancing::LoadBalancer,AWS::EC2::EIP
      - AWS::ElasticLoadBalancingV2::LoadBalancer,AWS::ElasticLoadBalancing::LoadBalancer
      - AWS::ElasticLoadBalancingV2::LoadBalancer,AWS::EC2::EIP
      - AWS::ElasticLoadBalancing::LoadBalancer,AWS::EC2::EIP
      - AWS::ElasticLoadBalancingV2::LoadBalancer
      - AWS::ElasticLoadBalancing::LoadBalancer
      - AWS::EC2::EIP
      - <na>
  ProtectCloudFront:
    Type: String
    Default: <na>
    AllowedValues:
      - AWS::CloudFront::Distribution
      - <na>
  ShieldAutoRemediate:
    Type: String
    Description: "Should in scope AWS resource types have Shield Advanced protection automatically be remediated?"
    Default: "Yes"
    AllowedValues:
      - "Yes"
      - "No"
  ScopeTagName1:
    Type: String
    Default: <na>
  ScopeTagName2:
    Type: String
    Default: <na>
  ScopeTagName3:
    Type: String
    Default: <na>
  ScopeTagValue1:
    Type: String
    Default: <na>
  ScopeTagValue2:
    Type: String
    Default: <na>
  ScopeTagValue3:
    Type: String
    Default: <na>


Conditions:
    ScopeTagName1Flag: !Not [!Equals [!Ref ScopeTagName1, "<na>"]]
    ScopeTagName2Flag: !Not [!Equals [!Ref ScopeTagName2, "<na>"]]
    ScopeTagName3Flag: !Not [!Equals [!Ref ScopeTagName3, "<na>"]]
    ScopeTagValue1Flag: !Not [!Equals [!Ref ScopeTagValue1, "<na>"]]
    ScopeTagValue2Flag: !Not [!Equals [!Ref ScopeTagValue2, "<na>"]]
    ScopeTagValue3Flag: !Not [!Equals [!Ref ScopeTagValue3, "<na>"]]
    ShieldAutoRemediateFlag: !Not [!Equals [!Ref ShieldAutoRemediate, "No"]]
    OUScopeFlag: !Equals [!Ref ScopeType, "OU"]
    AccountScopeFlag: !Equals [!Ref ScopeType, "Accounts"]
    ExcludeResourceTagFlag: !Equals [!Ref ResourceTagUsage, "Exclude"]
    IncludeScopeFlag: !Equals [!Ref IncludeExcludeScope, "Include"]
    ExcludeScopeFlag: !Equals [!Ref IncludeExcludeScope, "Exclude"]
    CreateRegionalPolicyFlag: !Not [!Equals [!Ref ProtectRegionalResourceTypes, '<na>'] ]
    CreateCloudFrontPolicyFlag: !And [ !Not [!Equals [!Ref ProtectCloudFront, "<na>"] ], !Equals [!Ref AWS::Region, 'us-east-1']]
Resources:
  ShieldRegionalResources:
    Condition: CreateRegionalPolicyFlag
    Type: AWS::FMS::Policy
    Properties:
      PolicyName: !Sub OneClickShieldRegional-${AWS::StackName}
      ResourceType: ResourceTypeList
      ResourceTypeList: !Split [",", !Ref ProtectRegionalResourceTypes]
      ExcludeResourceTags: !If [ExcludeResourceTagFlag, true, false]
      IncludeMap:
        ORGUNIT:
          !If [IncludeScopeFlag, !If [OUScopeFlag, !Split [",", !Ref ScopeDetails], !Ref "AWS::NoValue"], !Ref "AWS::NoValue"]
        ACCOUNT:
          !If [IncludeScopeFlag, !If [AccountScopeFlag, !Split [",", !Ref ScopeDetails] , !Ref "AWS::NoValue"], !Ref "AWS::NoValue"]
      ExcludeMap:
        ORGUNIT:
          !If [ExcludeScopeFlag, !If [OUScopeFlag, !Split [",", !Ref ScopeDetails], !Ref "AWS::NoValue"], !Ref "AWS::NoValue"]
        ACCOUNT:
          !If [ExcludeScopeFlag, !If [AccountScopeFlag, !Split [",", !Ref ScopeDetails], !Ref "AWS::NoValue"], !Ref "AWS::NoValue"]
      RemediationEnabled: !If [ShieldAutoRemediateFlag, true, false]
      SecurityServicePolicyData:
          Type: SHIELD_ADVANCED
      DeleteAllPolicyResources: false
      ResourceTags:
        !If
        - ScopeTagName1Flag
        -
          - !If
            - ScopeTagName1Flag
            - Key:  !Ref ScopeTagName1
              Value: !If [ScopeTagName1Flag, !Ref ScopeTagValue1, ""]
            - !Ref "AWS::NoValue"
          - !If
            - ScopeTagName2Flag
            - Key:  !Ref ScopeTagName2
              Value: !If [ScopeTagName2Flag, !Ref ScopeTagValue2, ""]
            - !Ref "AWS::NoValue"
          - !If
            - ScopeTagName3Flag
            - Key:  !Ref ScopeTagName3
              Value: !If [ScopeTagName3Flag, !Ref ScopeTagValue3, ""]
            - !Ref "AWS::NoValue"
        - !Ref "AWS::NoValue"
  ShieldCloudFrontResources:
    Condition: CreateCloudFrontPolicyFlag
    Type: AWS::FMS::Policy
    Properties:
      PolicyName: !Sub OneClickShieldGlobal-${AWS::StackName}
      ResourceType: AWS::CloudFront::Distribution
      ExcludeResourceTags: !If [ExcludeResourceTagFlag, true, false]
      IncludeMap:
        ORGUNIT:
          !If [IncludeScopeFlag, !If [OUScopeFlag, !Split [",", !Ref ScopeDetails], !Ref "AWS::NoValue"], !Ref "AWS::NoValue"]
        ACCOUNT:
          !If [IncludeScopeFlag, !If [AccountScopeFlag, !Split [",", !Ref ScopeDetails] , !Ref "AWS::NoValue"], !Ref "AWS::NoValue"]
      ExcludeMap:
        ORGUNIT:
          !If [ExcludeScopeFlag, !If [OUScopeFlag, !Split [",", !Ref ScopeDetails], !Ref "AWS::NoValue"], !Ref "AWS::NoValue"]
        ACCOUNT:
          !If [ExcludeScopeFlag, !If [AccountScopeFlag,  !Split [",", !Ref ScopeDetails], !Ref "AWS::NoValue"], !Ref "AWS::NoValue"]
      RemediationEnabled: !If [ShieldAutoRemediateFlag, true, false]
      SecurityServicePolicyData:
          Type: SHIELD_ADVANCED
      DeleteAllPolicyResources: false
      ResourceTags:
        !If
        - ScopeTagName1Flag
        -
          - !If
            - ScopeTagName1Flag
            - Key:  !Ref ScopeTagName1
              Value: !If [ScopeTagValue1Flag, !Ref ScopeTagValue1, ""]
            - !Ref "AWS::NoValue"
          - !If
            - ScopeTagName2Flag
            - Key:  !Ref ScopeTagName2
              Value: !If [ScopeTagValue2Flag, !Ref ScopeTagValue2, ""]
            - !Ref "AWS::NoValue"
          - !If
            - ScopeTagName3Flag
            - Key:  !Ref ScopeTagName3
              Value: !If [ScopeTagValue3Flag, !Ref ScopeTagValue3, ""]
            - !Ref "AWS::NoValue"
        - !Ref "AWS::NoValue"