### Logic Control variables
variable "fms_admin_account_id" {
  type = string
  description = "The account ID which has been designated as the FMS Administrator account (Default)"
}

variable "terraform_state_bucket_region" {
  type = string
}

variable "target_aws_account_region" {
  type = string
}

variable "target_account_id" {
  description = "DO NOT SET. This is generated by the python script. Used to identify the target account for each of the organizational deployment runs. "
  type = string
}

variable "scope_regions" {
  description = "DO NOT SET. This is generated by the output from core-deployment and passed via the pythong script. A comma separated list of AWS regions, e.g. us-east-1, us-east-2"
  type        = string
}

### sa_configure_subscribe module

variable "srt_access_role_name" {
  type    = string
  default = "<Generated>"
}

variable "srt_access_role_action" {
  type    = string
  default = "CreateRole"
  validation {
    condition     = contains(["CreateRole", "UseExisting"], var.srt_access_role_action)
    error_message = "Allowed values are [ CreateRole | UseExisting ]"
  }
}

variable "enable_srt_access" {
  type    = bool
  default = false
}

variable "enable_proactive_engagement" {
  type        = bool
  description = "Enable Proactive Engagement.  Note you must also configure emergency contact(s) and health checks for protected resources for this feature to be effective"
  default     = false
}

variable "srt_buckets" {
  type    = list(string)
  default = []
  validation {
    condition     = length(var.srt_buckets) <= 10
    error_message = "At most 10 buckets are allowed"
  }
}

variable "acknowledge_service_terms_pricing" {
  description = "Shield Advanced Service Term | Pricing | $3000 / month subscription fee for a consolidated billing family"
  type    = bool
  default = false
}

variable "acknowledge_service_terms_dto" {
  description = "Shield Advanced Service Term | Pricing | Data transfer out usage fees for all protected resources."
  type    = bool
  default = false
}

variable "acknowledge_service_terms_commitment" {
  description = "Shield Advanced Term | Commitment | I am committing to a 12 month subscription."
  type    = bool
  default = false
}

variable "acknowledge_service_terms_auto_renew" {
  description = "Shield Advanced Term | Auto renewal | Subscription will be auto-renewed after 12 months. However, I can opt out of renewal 30 days prior to the renewal date."
  type    = bool
  default = false
}

variable "acknowledge_no_unsubscribe" {
  description = "Shield Advanced does not un-subscribe on delete | Shield Advanced does not un-subscribe if you delete this stack/this resource."
  type    = bool
  default = false
}

variable "emergency_contact_email1" {
  type    = string
  default = "<na>"
  validation {
    condition     = can(regex("^\\S+@\\S+\\.\\S+$|<na>", var.emergency_contact_email1))
    error_message = "Invalid input for variable"
  }
}

variable "emergency_contact_email2" {
  type    = string
  default = "<na>"
  validation {
    condition     = can(regex("^\\S+@\\S+\\.\\S+$|<na>", var.emergency_contact_email2))
    error_message = "Invalid input for variable"
  }
}

variable "emergency_contact_email3" {
  type    = string
  default = "<na>"
  validation {
    condition     = can(regex("^\\S+@\\S+\\.\\S+$|<na>", var.emergency_contact_email3))
    error_message = "Invalid input for variable"
  }
}

variable "emergency_contact_email4" {
  type    = string
  default = "<na>"
  validation {
    condition     = can(regex("^\\S+@\\S+\\.\\S+$|<na>", var.emergency_contact_email4))
    error_message = "Invalid input for variable"
  }
}

variable "emergency_contact_email5" {
  type    = string
  default = "<na>"
  validation {
    condition     = can(regex("^\\S+@\\S+\\.\\S+$|<na>", var.emergency_contact_email5))
    error_message = "Invalid input for variable"
  }
}

variable "emergency_contact_phone1" {
  type    = string
  default = "<na>"
  validation {
    condition     = can(regex("^\\+[0-9]{11}|<na>", var.emergency_contact_phone1))
    error_message = "Invalid input for variable"
  }
}

variable "emergency_contact_phone2" {
  type    = string
  default = "<na>"
  validation {
    condition     = can(regex("^\\+[0-9]{11}|<na>", var.emergency_contact_phone2))
    error_message = "Invalid input for variable"
  }
}

variable "emergency_contact_phone3" {
  type    = string
  default = "<na>"
  validation {
    condition     = can(regex("^\\+[0-9]{11}|<na>", var.emergency_contact_phone3))
    error_message = "Invalid input for variable"
  }
}

variable "emergency_contact_phone4" {
  type    = string
  default = "<na>"
  validation {
    condition     = can(regex("^\\+[0-9]{11}|<na>", var.emergency_contact_phone4))
    error_message = "Invalid input for variable"
  }
}

variable "emergency_contact_phone5" {
  type    = string
  default = "<na>"
  validation {
    condition     = can(regex("^\\+[0-9]{11}|<na>", var.emergency_contact_phone5))
    error_message = "Invalid input for variable"
  }
}

variable "emergency_contact_note1" {
  type    = string
  default = "<na>"
  nullable = true
  validation {
    condition     = can(regex("^[\\w\\s\\.\\-,:/()+@]*$|<na>", var.emergency_contact_note1))
    error_message = "Invalid input for variable"
  }
}

variable "emergency_contact_note2" {
  type    = string
  default = "<na>"
  nullable = true

  validation {
    condition     = can(regex("^[\\w\\s\\.\\-,:/()+@]*$|<na>", var.emergency_contact_note2))
    error_message = "Invalid input for variable"
  }
}

variable "emergency_contact_note3" {
  type    = string
  default = "<na>"
  nullable = true
  validation {
    condition     = can(regex("^[\\w\\s\\.\\-,:/()+@]*$|<na>", var.emergency_contact_note3))
    error_message = "Invalid input for variable"
  }
}

variable "emergency_contact_note4" {
  type    = string
  default = "<na>"
  nullable = true
  validation {
    condition     = can(regex("^[\\w\\s\\.\\-,:/()+@]*$|<na>", var.emergency_contact_note4))
    error_message = "Invalid input for variable"
  }
}

variable "emergency_contact_note5" {
  type    = string
  default = "<na>"
  nullable = true
  validation {
    condition     = can(regex("^[\\w\\s\\.\\-,:/()+@]*$|<na>", var.emergency_contact_note5))
    error_message = "Invalid input for variable"
  }
}

### sa_fms_shield module

variable "scope_type" {
  description = "Should Firewall Manager Policies be scoped to the entire org (root) or a specific list of OUs (OU)"
  type        = string
  default     = "Org"
  validation {
    condition     = contains(["Org", "OU", "Accounts"], var.scope_type)
    error_message = "scope_type must be one of [ Org | OU | Accounts ]"
  }
}

variable "protect_regional_resource_types" {
  description = "AWS::ElasticLoadBalancingV2::LoadBalancer,AWS::ElasticLoadBalancing::LoadBalancer,AWS::EC2::EIP"
  type        = list(string)
  default     = ["AWS::ElasticLoadBalancingV2::LoadBalancer","AWS::ElasticLoadBalancing::LoadBalancer","AWS::EC2::EIP"]
}

variable "protect_cloud_front" {
  type    = string
  default = "<na>"
}

variable "shield_auto_remediate" {
  description = "Should in scope AWS resource types have Shield Advanced protection automatically be remediated?"
  type        = string
  default     = "Yes"
}

variable "scope_tag_name1" {
  type    = string
  default = "<na>"
}

variable "scope_tag_name2" {
  type    = string
  default = "<na>"
}

variable "scope_tag_name3" {
  type    = string
  default = "<na>"
}

variable "scope_tag_value1" {
  type    = string
  default = "<na>"
}

variable "scope_tag_value2" {
  type    = string
  default = "<na>"
}

variable "scope_tag_value3" {
  type    = string
  default = "<na>"
}

### sa_wafv2 module

variable "scope_details" {
  type    = list(string)
  default = []
}

variable "include_exclude_scope" {
  type    = string
  default = "Include"
  validation {
    condition     = contains(["Include", "Exclude"], var.include_exclude_scope)
    error_message = "Allowed values are [ Include | Exclude ]"
  }
}

variable "resource_tag_usage" {
  description = "Include will scope to only include when ResourceTags match, Exclude will exclude when target resource tags match ResourceTags"
  type        = string
  default     = "Include"
  validation {
    condition     = contains(["Include", "Exclude"], var.resource_tag_usage)
    error_message = "Allowed values are [ Include | Exclude ]"
  }
}

variable "wafv2_protect_regional_resource_types" {
  type    = string
  default = "AWS::ApiGateway::Stage,AWS::ElasticLoadBalancingV2::LoadBalancer"
  validation {
    condition     = contains(["AWS::ApiGateway::Stage,AWS::ElasticLoadBalancingV2::LoadBalancer", "AWS::ElasticLoadBalancingV2::LoadBalancer", "AWS::ApiGateway::Stage", "<na>"], var.wafv2_protect_regional_resource_types)
    error_message = "Allowed values are [ AWS::ApiGateway::Stage,AWS::ElasticLoadBalancingV2::LoadBalancer | AWS::ElasticLoadBalancingV2::LoadBalancer | AWS::ApiGateway::Stage | <na> ]"
  }
}

variable "wafv2_protect_cloudfront" {
  type    = string
  default = "<na>"
  validation {
    condition     = contains(["AWS::CloudFront::Distribution", "<na>"], var.wafv2_protect_cloudfront)
    error_message = "Allowed values are [ AWS::CloudFront::Distribution | <na> ]"
  }
}

variable "wafv2_auto_remediate" {
  description = "Should in scope AWS resource types that support AWS WAF automatically be remediated?"
  type        = string
  validation {
    condition     = contains(["Yes | Replace existing existing WebACL", "Yes | If no current WebACL", "No"], var.wafv2_auto_remediate)
    error_message = "Allowed values are [ 'Yes | Replace existing existing WebACL' | 'Yes | If no current WebACL' | 'No']"
  }
}

variable "scope_tag_name_1" {
  type    = string
  default = "<na>"
}

variable "scope_tag_name_2" {
  type    = string
  default = "<na>"
}

variable "scope_tag_name_3" {
  type    = string
  default = "<na>"
}

variable "scope_tag_value_1" {
  type    = string
  default = "<na>"
}

variable "scope_tag_value_2" {
  type    = string
  default = "<na>"
}

variable "scope_tag_value_3" {
  type    = string
  default = "<na>"
}

variable "rate_limit_value" {
  description = "AWS WAF rate limits use the previous 5 minutes to determine if an IP has exceeded the defined limit."
  type        = string
  default     = 10000
}

variable "rate_limit_action" {
  type    = string
  default = "Block"
  validation {
    condition     = contains(["Block", "Count"], var.rate_limit_action)
    error_message = "Allowed values are [ Block | Count ]"
  }
}

variable "anonymous_ip_amr_action" {
  description = "The Anonymous IP list rule group contains rules to block requests from services that permit the obfuscation of viewer identity. These include requests from VPNs, proxies, Tor nodes, and hosting providers. This rule group is useful if you want to filter out viewers that might be trying to hide their identity from your application."
  type        = string
  default     = "Block"
  validation {
    condition     = contains(["Block", "Count"], var.anonymous_ip_amr_action)
    error_message = "Allowed values are [ Block | Count ]"
  }
}

variable "ip_reputation_amr_action" {
  description = "The Amazon IP reputation list rule group contains rules that are based on Amazon internal threat intelligence. This is useful if you would like to block IP addresses typically associated with bots or other threats. Blocking these IP addresses can help mitigate bots and reduce the risk of a malicious actor discovering a vulnerable application."
  type        = string
  default     = "Block"
  validation {
    condition     = contains(["Block", "Count"], var.ip_reputation_amr_action)
    error_message = "Allowed values are [ Block | Count ]"
  }
}

variable "core_rule_set_amr_action" {
  description = "The Core rule set (CRS) rule group contains rules that are generally applicable to web applications. This provides protection against exploitation of a wide range of vulnerabilities, including some of the high risk and commonly occurring vulnerabilities described in OWASP publications such as OWASP Top 10"
  type        = string
  default     = "Count"
  validation {
    condition     = contains(["Block", "Count"], var.core_rule_set_amr_action)
    error_message = "Allowed values are [ Block | Count ]"
  }
}

variable "known_bad_inputs_amr_actions" {
  description = "The Known bad inputs rule group contains rules to block request patterns that are known to be invalid and are associated with exploitation or discovery of vulnerabilities. This can help reduce the risk of a malicious actor discovering a vulnerable application."
  type        = string
  default     = "Count"
  validation {
    condition     = contains(["Block", "Count"], var.known_bad_inputs_amr_actions)
    error_message = "Allowed values are [ Block | Count ]"
  }
}

variable "waf_log_s3_bucket_name" {
  type = string
}

variable "waf_delivery_role_arn" {
  type = string
}

variable "waf_log_kms_key_arn" {
  type = string
}